CC ?= gcc
CFLAGS ?= -Wall -Wextra -O2

all: uniwill_ibg10_fanctl

uniwill_ibg10_fanctl: uniwill_ibg10_fanctl.c
	$(CC) $(CFLAGS) -o uniwill_ibg10_fanctl uniwill_ibg10_fanctl.c

clean:
	rm -f uniwill_ibg10_fanctl
